/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.opencsvreader;

import org.junit.Test;

import com.bridgelabz.opencsvreader.OpenCSVReader;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
    }
}
