/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.opencsvreader;

public class OpenCSVReader {
    public boolean someLibraryMethod() {
        return true;
    }
}
